import pandas as pd
import google.auth
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="C:\\Users\diego\Documents\Burnout\Burnout\\burnout-c831a7220a8d.json"
project='burnout-258011'
credentials,project = google.auth.default(scopes=['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/bigquery',])


queryDatosFisiologicos = ('SELECT Burnout_Antes as Burnout,avg(Calorias) as Calorias, avg(Frecuencia_Cardiaca_Minuto) as Frecuencia_Cardiaca_Minuto ,avg(Resting_HeartRate) as Resting_HeartRate,avg(Eficiencia_Sueno) as Eficiencia_Sueno, avg(Peso) as Peso,avg(Hijos) as Hijos,avg(Tiempo_PlazaActual) as Tiempo_Plaza,avg( Tiempo_Vida_Laboral) as Tiempo_Vida_Laboral,avg(Max_HeartRate)as Max_HeartRate,avg( Min_HeartRate) as Min_HeartRate,avg( Duracion_Sueno ) as Duracion_Sueno,avg( Minutos_Rem ) as Minutos_Rem ,avg( Cantidad_Sueno_Profundo) as SuenoProfundo,avg( Minutos_Sueno_Profundo)as Min_SuenoProfundo,avg( Minutos_Sueno_Ligero) as Min_SuenoLigero, avg (Minutos_Sueno_Wake) as Minutos_SuenoDespierto, avg( Minutos_Dormido) as Min_Dormido, avg( Minutos_Despierto_enCama) Min_Despierto_enCama, avg( Tiempo_enCama) as Tiempo_enCama FROM `burnout-258011.burnout.burnout_Data` group by Burnout_Antes')
df_DatosFisiologicos = pd.read_gbq(queryDatosFisiologicos, project_id=project, dialect='standard')
df_DatosFisiologicos["Burnout"].replace({True: "VERDADERO", False: "FALSO"}, inplace=True)

queryPCA = ('SELECT * FROM `burnout-258011.burnout.Burnout_PCA`')
df_PCA= pd.read_gbq(queryDatosFisiologicos, project_id=project, dialect='standard')

queryDatosFisiologicosIndividuales = ('SELECT Email,avg(Calorias) as Calorias, avg(Frecuencia_Cardiaca_Minuto) as Frecuencia_Cardiaca_Minuto ,avg(Resting_HeartRate) as Resting_HeartRate,avg(Eficiencia_Sueno) as Eficiencia_Sueno, avg(Peso) as Peso,avg(Hijos) as Hijos,avg(Tiempo_PlazaActual) as Tiempo_Plaza,avg( Tiempo_Vida_Laboral) as Tiempo_Vida_Laboral,avg(Max_HeartRate)as Max_HeartRate,avg( Min_HeartRate) as Min_HeartRate,avg( Minutos_Rem ) as Minutos_Rem ,avg( Cantidad_Sueno_Profundo) as SuenoProfundo,avg( Minutos_Sueno_Profundo)as Min_SuenoProfundo,avg( Minutos_Sueno_Ligero) as Min_SuenoLigero, avg (Minutos_Sueno_Wake) as Minutos_SuenoDespierto, avg( Minutos_Dormido) as Min_Dormido, avg( Minutos_Despierto_enCama) Min_Despierto_enCama, avg( Tiempo_enCama) as Tiempo_enCama, avg( Cansancio_Emocional) as Cansancio_Emocional,avg( Despersonalizacion) as Despersonalizacion, avg( Realizacion_Personal) as Realizacion_Personal, avg( Altura) as Altura,avg (Tiempo_PlazaActual) as Tiempo_PlazaActual, avg(Ultima_Encuesta_Cansancio_Emocional) as Ultima_Encuesta_Cansancio_Emocional, avg( Ultima_Encuesta_Despersonalizacion) as Ultima_Encuesta_Despersonalizacion, avg( Ultima_Encuesta_Realizacion_Personal) as Ultima_Encuesta_Realizacion_Personal, avg( Horas_Cuidados) as Horas_Cuidados,avg( Horas_Activ_Fisica) as Horas_Activ_Fisica, avg( Hora_Gratificante) as Hora_Gratificante, avg( Hora_Social) as Hora_Social FROM `burnout-258011.burnout.burnout_Data` group by Email')
df_DatosFisiologicosIndividuales = pd.read_gbq(queryDatosFisiologicosIndividuales, project_id=project, dialect='standard')

querySubescalasBurnout = ('SELECT avg(Cansancio_Emocional) as Cansancio_Emocional , avg(Despersonalizacion) as Despersonalizacion, avg(Realizacion_Personal) as Realizacion_Personal, avg(Ultima_Encuesta_Realizacion_Personal) as Ultima_Encuesta_Realizacion_Personal, avg(Ultima_Encuesta_Despersonalizacion) as Ultima_Encuesta_Despersonalizacion, avg(Ultima_Encuesta_Cansancio_Emocional) as Ultima_Encuesta_Cansancio_Emocional,Burnout_Antes,Burnout_Despues FROM `burnout-258011.burnout.burnout_Data` group by Burnout_Antes, Burnout_Despues')
df_SubescalasBurnout = pd.read_gbq(querySubescalasBurnout, project_id=project, dialect='standard')
df_SubescalasBurnout["Burnout_Antes"].replace({True: "VERDADERO", False: "FALSO"}, inplace=True)
df_SubescalasBurnout["Burnout_Despues"].replace({True: "VERDADERO", False: "FALSO"}, inplace=True)

querySubescalasIndividual = ('SELECT avg(Cansancio_Emocional) as Cansancio_Emocional , avg(Despersonalizacion) as Despersonalizacion, avg(Realizacion_Personal) as Realizacion_Personal, avg(Ultima_Encuesta_Realizacion_Personal) as Ultima_Encuesta_Realizacion_Personal, avg(Ultima_Encuesta_Despersonalizacion) as Ultima_Encuesta_Despersonalizacion, avg(Ultima_Encuesta_Cansancio_Emocional) as Ultima_Encuesta_Cansancio_Emocional,Burnout_Antes,Burnout_Despues, Email as Identificador FROM `burnout-258011.burnout.burnout_Data` group by Burnout_Antes, Burnout_Despues, Email')
df_SubescalasIndividual = pd.read_gbq(querySubescalasIndividual, project_id=project, dialect='standard')
df_SubescalasIndividual["Burnout_Antes"].replace({True: "0", False: "1"}, inplace=True)
df_SubescalasIndividual["Burnout_Despues"].replace({True: "0", False: "1"}, inplace=True)


queryporEspecialidad = ('SELECT Especialidad,avg(Calorias) as Calorias, avg(Frecuencia_Cardiaca_Minuto) as Frecuencia_Cardiaca_Minuto ,avg(Resting_HeartRate) as Resting_HeartRate,avg(Eficiencia_Sueno) as Eficiencia_Sueno, avg(Peso) as Peso,avg(Hijos) as Hijos,avg(Tiempo_PlazaActual) as Tiempo_Plaza,avg( Tiempo_Vida_Laboral) as Tiempo_Vida_Laboral,avg(Max_HeartRate)as Max_HeartRate,avg( Min_HeartRate) as Min_HeartRate,avg( Minutos_Rem ) as Minutos_Rem ,avg( Cantidad_Sueno_Profundo) as SuenoProfundo,avg( Minutos_Sueno_Profundo)as Min_SuenoProfundo,avg( Minutos_Sueno_Ligero) as Min_SuenoLigero, avg (Minutos_Sueno_Wake) as Minutos_SuenoDespierto, avg( Minutos_Dormido) as Min_Dormido, avg( Minutos_Despierto_enCama) Min_Despierto_enCama, avg( Tiempo_enCama) as Tiempo_enCama, avg( Cansancio_Emocional) as Cansancio_Emocional,avg( Despersonalizacion) as Despersonalizacion, avg( Realizacion_Personal) as Realizacion_Personal  FROM `burnout-258011.burnout.burnout_Data` group by Especialidad')
df_Especialidad = pd.read_gbq(queryporEspecialidad, project_id=project, dialect='standard')

queryporSexo = ('SELECT Sexo,avg(Calorias) as Calorias, avg(Frecuencia_Cardiaca_Minuto) as Frecuencia_Cardiaca_Minuto ,avg(Resting_HeartRate) as Resting_HeartRate,avg(Eficiencia_Sueno) as Eficiencia_Sueno, avg(Peso) as Peso,avg(Hijos) as Hijos,avg(Tiempo_PlazaActual) as Tiempo_Plaza,avg( Tiempo_Vida_Laboral) as Tiempo_Vida_Laboral,avg(Max_HeartRate)as Max_HeartRate,avg( Min_HeartRate) as Min_HeartRate,avg( Minutos_Rem ) as Minutos_Rem ,avg( Cantidad_Sueno_Profundo) as SuenoProfundo,avg( Minutos_Sueno_Profundo)as Min_SuenoProfundo,avg( Minutos_Sueno_Ligero) as Min_SuenoLigero, avg (Minutos_Sueno_Wake) as Minutos_SuenoDespierto, avg( Minutos_Dormido) as Min_Dormido, avg( Minutos_Despierto_enCama) Min_Despierto_enCama, avg( Tiempo_enCama) as Tiempo_enCama, avg( Cansancio_Emocional) as Cansancio_Emocional,avg( Despersonalizacion) as Despersonalizacion, avg( Realizacion_Personal) as Realizacion_Personal  FROM `burnout-258011.burnout.burnout_Data` group by Sexo')
df_Sexo = pd.read_gbq(queryporSexo, project_id=project, dialect='standard')
